site_name: Yuuki's Homelab

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.svg

  features:
    - content.code.copy

  palette:

    - scheme: default
      toggle:
        icon: material/weather-night

    - scheme: slate
      toggle:
        icon: material/weather-sunny
