site_name: Yuuki's Homelab

theme:
  name: material

  features:
    - content.code.copy

  palette:

    - scheme: default
      toggle:
        icon: material/weather-night

    - scheme: slate
      toggle:
        icon: material/weather-sunny
